using System.Linq;
using Content.Shared._Sich.Hunter.Autodoc;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Client.UserInterface.Controls;

namespace Content.Client._Sich.Hunter.Autodoc.UI;

[GenerateTypedNameReferences]
public sealed partial class AutodocHunterWindow : DefaultWindow
{
    public Action? OnAutoHealPressed;
    public Action<EntProtoId, EntProtoId, EntityUid>? OnSurgeryStepPressed;

    public AutodocHunterWindow()
    {
        RobustXamlLoader.Load(this);

        AutoHealButton.OnPressed += _ => OnAutoHealPressed?.Invoke();
    }

    public void UpdateState(AutodocHunterBuiState state)
    {
        StatusLabel.Text = Loc.GetString(state.IsHealing ? "autodoc-hunter-status-healing" : "autodoc-hunter-status-idle");
        
        // Disable AutoHeal button if healing is active, or change text
        AutoHealButton.Text = Loc.GetString(state.IsHealing ? "autodoc-hunter-auto-heal-stop" : "autodoc-hunter-auto-heal-start");

        SurgeryOptionsContainer.RemoveAllChildren();

        if (state.SurgeryOptions == null || state.SurgeryOptions.Count == 0)
        {
            var label = new Label { Text = Loc.GetString("autodoc-hunter-no-surgeries"), FontColorOverride = Color.Gray };
            SurgeryOptionsContainer.AddChild(label);
            return;
        }

        foreach (var option in state.SurgeryOptions)
        {
            var btn = new Button
            {
                Text = $"{Loc.GetString("autodoc-hunter-perform")} {Loc.GetString(option.Name)}",
                Margin = new Thickness(0, 0, 0, 4)
            };
            btn.OnPressed += _ => OnSurgeryStepPressed?.Invoke(option.Surgery, option.Step, option.Part);
            SurgeryOptionsContainer.AddChild(btn);
        }
    }
}
